name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Create build directory
      run: mkdir build && cd build

    - name: Configure
      run: cmake ..

    - name: Build
      run: make -j4

    - name: Test
      run: make test -j4